---
abstract: 'Logger suitable for use with TAP test files'
author:
  - 'Michael Conrad <mike@nrdvana.net>'
build_requires:
  Exporter: '0'
  FindBin: '0'
  Log::Any::Adapter: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Any-Adapter-TAP
requires:
  Carp: '0'
  Data::Dumper: '0'
  Log::Any: '0'
  Log::Any::Adapter::Base: '0'
  Log::Any::Proxy: '0'
  Scalar::Util: '0'
  Try::Tiny: '0'
  parent: '0'
  perl: v5.6.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/silverdirk/perl-Log-Any-Adapter-TAP/issues
  homepage: https://github.com/silverdirk/perl-Log-Any-Adapter-TAP
  repository: git://github.com/silverdirk/perl-Log-Any-Adapter-TAP.git
version: '0.003003'
